/**
 * These profiles were generated by ChatGPT.
 * 
 * Prompt:
 * 
 * I have 5 post genres: humor, nature, motivational, educational, and misc.
 * Output an array of JSON objects representing a social media profile
 * with a name (ex. name: 'todd-naturelover22') and a genre (ex. genre: 'nature').
 */
let profiles = [
    { "name": "todd-naturelover22", "genre": "nature" },
    { "name": "laughs.by.lena", "genre": "humor" },
    { "name": "zen.mode.zack", "genre": "motivational" },
    { "name": "brainy.bree", "genre": "educational" },
    { "name": "random.rae", "genre": "misc" },
    { "name": "mossy.miles", "genre": "nature" },
    { "name": "joke.jay", "genre": "humor" },
    { "name": "rise.with.riley", "genre": "motivational" },
    { "name": "facts.for.felix", "genre": "educational" },
    { "name": "bits.and.bobs", "genre": "misc" }
  ]